<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TransportUnit;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $units = [
            ['name' => 'Volvo FH16', 'type' => 'truck'],
    ['name' => 'Scania R500', 'type' => 'truck'],
    ['name' => 'DAF XF', 'type' => 'truck'],
    ['name' => 'Mercedes-Benz Actros', 'type' => 'truck'],
    ['name' => 'MAN TGX', 'type' => 'truck'],
    ['name' => 'Iveco S-Way', 'type' => 'truck'],
    ['name' => 'Renault T High', 'type' => 'truck'],
    ['name' => 'Kenworth W900', 'type' => 'truck'],
    ['name' => 'Peterbilt 579', 'type' => 'truck'],
    ['name' => 'Freightliner Cascadia', 'type' => 'truck'],
    ['name' => 'Mack Anthem', 'type' => 'truck'],
    ['name' => 'Western Star 49X', 'type' => 'truck'],
    ['name' => 'Scania S730', 'type' => 'truck'],
    ['name' => 'Hino 700', 'type' => 'truck'],
    ['name' => 'Ford F-Max', 'type' => 'truck'],
    ['name' => 'Volvo VNL', 'type' => 'truck'],
    ['name' => 'International LT', 'type' => 'truck'],
    ['name' => 'Mercedes-Benz Arocs', 'type' => 'truck'],
    ['name' => 'Isuzu Giga', 'type' => 'truck'],
    ['name' => 'Tatra Phoenix', 'type' => 'truck'],
    ['name' => 'Schmitz Cargobull Reefer', 'type' => 'trailer'],
    ['name' => 'Krone Dry Liner', 'type' => 'trailer'],
    ['name' => 'Faymonville MultiMAX', 'type' => 'trailer'],
    ['name' => 'Kögel Cargo', 'type' => 'trailer'],
    ['name' => 'Chereau Refrigerated', 'type' => 'trailer'],
    ['name' => 'Lamberet SR2', 'type' => 'trailer'],
    ['name' => 'Wielton Curtain Sider', 'type' => 'trailer'],
    ['name' => 'Utility 3000R', 'type' => 'trailer'],
    ['name' => 'Great Dane Everest', 'type' => 'trailer'],
    ['name' => 'Stoughton Dry Van', 'type' => 'trailer'],
    ['name' => 'Fruehauf Dry Van', 'type' => 'trailer'],
    ['name' => 'MAC Aluminum Flatbed', 'type' => 'trailer'],
    ['name' => 'Fontaine Revolution', 'type' => 'trailer'],
    ['name' => 'Trail King Lowboy', 'type' => 'trailer'],
    ['name' => 'Manac Chip Trailer', 'type' => 'trailer'],
    ['name' => 'East Genesis Dump', 'type' => 'trailer'],
    ['name' => 'CIMC Refrigerated', 'type' => 'trailer'],
    ['name' => 'Hyundai Translead', 'type' => 'trailer'],
    ['name' => 'Doepker Super B-Train', 'type' => 'trailer'],
    ['name' => 'Felling Hydraulic Tail', 'type' => 'trailer'],
    ['name' => 'Reitnouer Aluminum', 'type' => 'trailer'],
    ['name' => 'Benson Flatbed', 'type' => 'trailer'],
    ['name' => 'Timpte Super Hopper', 'type' => 'trailer'],
    ['name' => 'Vanguard VXP', 'type' => 'trailer'],
    ['name' => 'Polar Tank Trailer', 'type' => 'trailer'],
    ['name' => 'Kentucky Trailer', 'type' => 'trailer'],
    ['name' => 'Wabash Dry Van', 'type' => 'trailer'],
    ['name' => 'Strick Dry Van', 'type' => 'trailer'],
    ['name' => 'Trail-Eze Hydraulic', 'type' => 'trailer'],
    ['name' => 'Talbert Lowboy', 'type' => 'trailer'],
    ['name' => 'Beall Tank Trailer', 'type' => 'trailer'],
    ['name' => 'Pitts Log Trailer', 'type' => 'trailer'],
    ['name' => 'Volvo FH16', 'type' => 'truck'],
    ['name' => 'Scania R500', 'type' => 'truck'],
    ['name' => 'DAF XF', 'type' => 'truck'],
    ['name' => 'Mercedes-Benz Actros', 'type' => 'truck'],
    ['name' => 'MAN TGX', 'type' => 'truck'],
    ['name' => 'Iveco S-Way', 'type' => 'truck'],
    ['name' => 'Renault T High', 'type' => 'truck'],
    ['name' => 'Kenworth W900', 'type' => 'truck'],
    ['name' => 'Peterbilt 579', 'type' => 'truck'],
    ['name' => 'Freightliner Cascadia', 'type' => 'truck'],
    ['name' => 'Mack Anthem', 'type' => 'truck'],
    ['name' => 'Western Star 49X', 'type' => 'truck'],
    ['name' => 'Scania S730', 'type' => 'truck'],
    ['name' => 'Hino 700', 'type' => 'truck'],
    ['name' => 'Ford F-Max', 'type' => 'truck'],
    ['name' => 'Volvo VNL', 'type' => 'truck'],
    ['name' => 'International LT', 'type' => 'truck'],
    ['name' => 'Mercedes-Benz Arocs', 'type' => 'truck'],
    ['name' => 'Isuzu Giga', 'type' => 'truck'],
    ['name' => 'Tatra Phoenix', 'type' => 'truck'],
    ['name' => 'Schmitz Cargobull Reefer', 'type' => 'trailer'],
    ['name' => 'Krone Dry Liner', 'type' => 'trailer'],
    ['name' => 'Faymonville MultiMAX', 'type' => 'trailer'],
    ['name' => 'Kögel Cargo', 'type' => 'trailer'],
    ['name' => 'Chereau Refrigerated', 'type' => 'trailer'],
    ['name' => 'Lamberet SR2', 'type' => 'trailer'],
    ['name' => 'Wielton Curtain Sider', 'type' => 'trailer'],
    ['name' => 'Utility 3000R', 'type' => 'trailer'],
    ['name' => 'Great Dane Everest', 'type' => 'trailer'],
    ['name' => 'Stoughton Dry Van', 'type' => 'trailer'],
    ['name' => 'Fruehauf Dry Van', 'type' => 'trailer'],
    ['name' => 'MAC Aluminum Flatbed', 'type' => 'trailer'],
    ['name' => 'Fontaine Revolution', 'type' => 'trailer'],
    ['name' => 'Trail King Lowboy', 'type' => 'trailer'],
    ['name' => 'Manac Chip Trailer', 'type' => 'trailer'],
    ['name' => 'East Genesis Dump', 'type' => 'trailer'],
    ['name' => 'CIMC Refrigerated', 'type' => 'trailer'],
    ['name' => 'Hyundai Translead', 'type' => 'trailer'],
    ['name' => 'Doepker Super B-Train', 'type' => 'trailer'],
    ['name' => 'Felling Hydraulic Tail', 'type' => 'trailer'],
    ['name' => 'Reitnouer Aluminum', 'type' => 'trailer'],
    ['name' => 'Paccar MX-13', 'type' => 'truck'],
    ['name' => 'Navistar International Lonestar', 'type' => 'truck'],
    ['name' => 'GMC TopKick', 'type' => 'truck'],
    ['name' => 'Isuzu NPR', 'type' => 'truck'],
    ['name' => 'Sterling A9500', 'type' => 'truck'],
    ['name' => 'Kenworth T680', 'type' => 'truck'],
    ['name' => 'Western Star 5700XE', 'type' => 'truck'],
    ['name' => 'Mitsubishi Fuso Super Great', 'type' => 'truck'],
    ['name' => 'Ford L9000', 'type' => 'truck'],
    ['name' => 'Volvo FH540', 'type' => 'truck'],
    ['name' => 'Freightliner M2', 'type' => 'truck'],
    ['name' => 'Peterbilt 389', 'type' => 'truck'],
    ['name' => 'Timpte Super Hopper', 'type' => 'trailer'],
    ['name' => 'Etnyre Lowboy', 'type' => 'trailer'],
    ['name' => 'Lode King Prestige', 'type' => 'trailer'],
    ['name' => 'Benson Aluminum Flatbed', 'type' => 'trailer'],
    ['name' => 'Vanguard Dry Freight', 'type' => 'trailer'],
    ['name' => 'Talbert Lowboy', 'type' => 'trailer'],
    ['name' => 'Stargate Aluminum Dump', 'type' => 'trailer'],
    ['name' => 'Kassbohrer Low Loader', 'type' => 'trailer'],
    ['name' => 'Böckmann Big Master', 'type' => 'trailer'],
    ['name' => 'Goldhofer STZ-VP', 'type' => 'trailer']
        ];
    
        foreach ($units as $unit) {
            TransportUnit::create($unit);
        }
    }
}
